name: My First Github Action

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - run: tree

      - name: Step 1
        run: echo "Hello World!"

      - name: Step 2
        run: echo "this is step no. 2"
