name: My First Github Action

on:
  push:
    branches:
      - master

jobs:
  build-app:
    name: Build & Deploy Vite App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: node -v

      - run: npm ci

      - run: npm run build

      - name: Deploying the project
        run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Setup finish
        run: echo "Hurray!!"
