name: My First Github Action

on: [push]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Hello World!"

      - name: Step 2
        run: echo "this is step no. 2"
